GS2TemplateFormatVersion: "2019-05-01"
Resources:
  ExchangeCurrentRateMaster_LimitAdUse:
    Type: "GS2::Exchange::CurrentRateMaster"
    Properties:
      NamespaceName: "LimitAdUse"
      Settings:
        version: "2019-08-19"
        rateModels:
          - name: "daily"
            verifyActions: []
            consumeActions:
              - action: "Gs2AdReward:ConsumePointByUserId"
                request: "{\"namespaceName\":\"Ad\",\"userId\":\"#{userId}\",\"point\":1}"
              - action: "Gs2Limit:CountUpByUserId"
                request: "{\"namespaceName\":\"Limit\",\"limitName\":\"daily\",\"counterName\":\"daily\",\"userId\":\"#{userId}\",\"countUpValue\":1,\"maxValue\":5}"
            acquireActions: []
        incrementalRateModels: []
      Mode: "direct"
    DependsOn:
      - "ExchangeNamespace_LimitAdUse"
  ExchangeCurrentRateMaster_LimitFreeUse:
    Type: "GS2::Exchange::CurrentRateMaster"
    Properties:
      NamespaceName: "LimitFreeUse"
      Settings:
        version: "2019-08-19"
        rateModels:
          - name: "daily"
            verifyActions: []
            consumeActions:
              - action: "Gs2Limit:CountUpByUserId"
                request: "{\"namespaceName\":\"Limit\",\"limitName\":\"daily\",\"counterName\":\"daily\",\"userId\":\"#{userId}\",\"countUpValue\":1,\"maxValue\":3}"
            acquireActions: []
        incrementalRateModels: []
      Mode: "direct"
    DependsOn:
      - "ExchangeNamespace_LimitFreeUse"
  ExchangeCurrentRateMaster_LimitReset:
    Type: "GS2::Exchange::CurrentRateMaster"
    Properties:
      NamespaceName: "LimitReset"
      Settings:
        version: "2019-08-19"
        rateModels:
          - name: "daily"
            verifyActions: []
            consumeActions: []
            acquireActions:
              - action: "Gs2Limit:DeleteCounterByUserId"
                request: "{\"namespaceName\":\"Limit\",\"limitName\":\"daily\",\"userId\":\"#{userId}\",\"counterName\":\"daily\"}"
        incrementalRateModels: []
      Mode: "direct"
    DependsOn:
      - "ExchangeNamespace_LimitReset"
  ExchangeNamespace_LimitAdUse:
    Type: "GS2::Exchange::Namespace"
    Properties:
      Name: "LimitAdUse"
      TransactionSetting:
        AcquireActionUseJobQueue: false
        DistributorNamespaceId: "grn:gs2:{region}:{ownerId}:distributor:default"
        EnableAtomicCommit: true
        EnableAutoRun: true
        QueueNamespaceId: "grn:gs2:{region}:{ownerId}:queue:default"
        TransactionUseDistributor: false
  ExchangeNamespace_LimitFreeUse:
    Type: "GS2::Exchange::Namespace"
    Properties:
      Name: "LimitFreeUse"
      TransactionSetting:
        AcquireActionUseJobQueue: false
        DistributorNamespaceId: "grn:gs2:{region}:{ownerId}:distributor:default"
        EnableAtomicCommit: true
        EnableAutoRun: true
        QueueNamespaceId: "grn:gs2:{region}:{ownerId}:queue:default"
        TransactionUseDistributor: false
  ExchangeNamespace_LimitReset:
    Type: "GS2::Exchange::Namespace"
    Properties:
      Name: "LimitReset"
      TransactionSetting:
        AcquireActionUseJobQueue: false
        DistributorNamespaceId: "grn:gs2:{region}:{ownerId}:distributor:default"
        EnableAtomicCommit: true
        EnableAutoRun: true
        QueueNamespaceId: "grn:gs2:{region}:{ownerId}:queue:default"
        TransactionUseDistributor: false
