GS2TemplateFormatVersion: "2019-05-01"
Resources:
  ExchangeCurrentRateMaster_EnergyProduct:
    Type: "GS2::Exchange::CurrentRateMaster"
    Properties:
      NamespaceName: "EnergyProduct"
      Settings:
        version: "2019-08-19"
        rateModels:
          - name: "refill_large"
            verifyActions: []
            consumeActions:
              - action: "Gs2Money2:WithdrawByUserId"
                request: "{\"namespaceName\":\"Currency\",\"userId\":\"#{userId}\",\"slot\":0,\"withdrawCount\":100,\"paidOnly\":false}"
            acquireActions: []
          - name: "refill_medium"
            verifyActions: []
            consumeActions:
              - action: "Gs2Money2:WithdrawByUserId"
                request: "{\"namespaceName\":\"Currency\",\"userId\":\"#{userId}\",\"slot\":0,\"withdrawCount\":70,\"paidOnly\":false}"
            acquireActions: []
          - name: "refill_small"
            verifyActions: []
            consumeActions:
              - action: "Gs2Money2:WithdrawByUserId"
                request: "{\"namespaceName\":\"Currency\",\"userId\":\"#{userId}\",\"slot\":0,\"withdrawCount\":30,\"paidOnly\":false}"
            acquireActions: []
        incrementalRateModels: []
      Mode: "direct"
    DependsOn:
      - "ExchangeNamespace_EnergyProduct"
  ExchangeNamespace_EnergyProduct:
    Type: "GS2::Exchange::Namespace"
    Properties:
      Name: "EnergyProduct"
      TransactionSetting:
        DistributorNamespaceId: "grn:gs2:{region}:{ownerId}:distributor:default"
        EnableAutoRun: false
        QueueNamespaceId: "grn:gs2:{region}:{ownerId}:queue:default"
