GS2TemplateFormatVersion: "2019-05-01"
Resources:
  Ranking2CurrentRankingMaster_GuildRanking:
    Type: "GS2::Ranking2::CurrentRankingMaster"
    Properties:
      NamespaceName: "GuildRanking"
      Settings:
        version: "2024-05-30"
        globalRankingModels: []
        clusterRankingModels:
          - clusterType: "Gs2Guild::Guild"
            maximumValue: 100
            metadata: ""
            minimumValue: 1
            name: "guild"
            orderDirection: "desc"
            rewardCalculationIndex: "rank"
            sum: true
            entryPeriodEventId: "grn:gs2:{region}:{ownerId}:schedule:Schedule:event:guild-season"
            rankingRewards:
              - metadata: "{\"thresholdRank\":{\"present\":true,\"value\":1},\"ranking\":{\"present\":true,\"value\":\"guild\"}}"
                thresholdRank: 1
                acquireActions:
                  - action: "Gs2Money2:DepositByUserId"
                    request: "{\"namespaceName\":\"Currency\",\"userId\":\"#{userId}\",\"slot\":0,\"depositTransactions\":[{\"price\":0,\"currency\":\"\",\"count\":300}]}"
              - metadata: "{\"thresholdRank\":{\"present\":true,\"value\":10},\"ranking\":{\"present\":true,\"value\":\"guild\"}}"
                thresholdRank: 10
                acquireActions:
                  - action: "Gs2Money2:DepositByUserId"
                    request: "{\"namespaceName\":\"Currency\",\"userId\":\"#{userId}\",\"slot\":0,\"depositTransactions\":[{\"price\":0,\"currency\":\"\",\"count\":50}]}"
              - metadata: "{\"thresholdRank\":{\"present\":true,\"value\":3},\"ranking\":{\"present\":true,\"value\":\"guild\"}}"
                thresholdRank: 3
                acquireActions:
                  - action: "Gs2Money2:DepositByUserId"
                    request: "{\"namespaceName\":\"Currency\",\"userId\":\"#{userId}\",\"slot\":0,\"depositTransactions\":[{\"price\":0,\"currency\":\"\",\"count\":150}]}"
        subscribeRankingModels: []
      Mode: "direct"
    DependsOn:
      - "Ranking2Namespace_GuildRanking"
  Ranking2Namespace_GuildRanking:
    Type: "GS2::Ranking2::Namespace"
    Properties:
      Name: "GuildRanking"
      TransactionSetting:
        AcquireActionUseJobQueue: false
        DistributorNamespaceId: "grn:gs2:{region}:{ownerId}:distributor:default"
        EnableAtomicCommit: true
        EnableAutoRun: true
        QueueNamespaceId: "grn:gs2:{region}:{ownerId}:queue:default"
        TransactionUseDistributor: false
