GS2TemplateFormatVersion: "2019-05-01"
Resources:
  ExchangeCurrentRateMaster_CharacterDictionaryMark:
    Type: "GS2::Exchange::CurrentRateMaster"
    Properties:
      NamespaceName: "CharacterDictionaryMark"
      Settings:
        version: "2019-08-19"
        rateModels:
          - name: "archer"
            verifyActions: []
            consumeActions: []
            acquireActions:
              - action: "Gs2Dictionary:AddEntriesByUserId"
                request: "{\"namespaceName\":\"CharacterDictionary\",\"userId\":\"#{userId}\",\"entryModelNames\":[\"archer\"]}"
          - name: "healer"
            verifyActions: []
            consumeActions: []
            acquireActions:
              - action: "Gs2Dictionary:AddEntriesByUserId"
                request: "{\"namespaceName\":\"CharacterDictionary\",\"userId\":\"#{userId}\",\"entryModelNames\":[\"healer\"]}"
          - name: "knight"
            verifyActions: []
            consumeActions: []
            acquireActions:
              - action: "Gs2Dictionary:AddEntriesByUserId"
                request: "{\"namespaceName\":\"CharacterDictionary\",\"userId\":\"#{userId}\",\"entryModelNames\":[\"knight\"]}"
          - name: "mage"
            verifyActions: []
            consumeActions: []
            acquireActions:
              - action: "Gs2Dictionary:AddEntriesByUserId"
                request: "{\"namespaceName\":\"CharacterDictionary\",\"userId\":\"#{userId}\",\"entryModelNames\":[\"mage\"]}"
        incrementalRateModels: []
      Mode: "direct"
    DependsOn:
      - "ExchangeNamespace_CharacterDictionaryMark"
  ExchangeNamespace_CharacterDictionaryMark:
    Type: "GS2::Exchange::Namespace"
    Properties:
      Name: "CharacterDictionaryMark"
      TransactionSetting:
        AcquireActionUseJobQueue: false
        DistributorNamespaceId: "grn:gs2:{region}:{ownerId}:distributor:default"
        EnableAtomicCommit: true
        EnableAutoRun: true
        QueueNamespaceId: "grn:gs2:{region}:{ownerId}:queue:default"
        TransactionUseDistributor: false
